version: "3"

services:
  postgres_test:
    image: postgres
    command: postgres -c log_statement=all
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tests
